Migrate to Core
rescript-association/rescript-lang.org pull request #876
Opened 2024-06-02 21:56 UTC by aspeddro

2024-06-03 01:16 UTC, aspeddro commented on README.md
> +- `node@20` or higher
Core has bindings to `Array.toSorted`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted require node v20

2024-06-03 01:21 UTC, aspeddro commented on src/common/Util.res
> -
We can use `JSON.stringify(json, ~space=2)`

2024-06-03 16:49 UTC, fhammerschmidt commented on src/components/SearchBox.res
> +    let isDiv = Nullable.toOption(el["type"])->Option.isSome
not really, as it is not optimized by the compiler in the null case
I am not really sure why this did not make it into Core, @zth ?

2024-06-03 16:51 UTC, zth commented on src/components/SearchBox.res
> +    let isDiv = Nullable.toOption(el["type"])->Option.isSome
Which one?

2024-06-03 16:52 UTC, fhammerschmidt commented on src/components/SearchBox.res
> +    let isDiv = Nullable.toOption(el["type"])->Option.isSome
`Js.Null_undefined.isNullable`

2024-06-03 16:52 UTC, fhammerschmidt commented on src/components/SearchBox.res
> +    let isDiv = Nullable.toOption(el["type"])->Option.isSome
it's just
`external isNullable: t<'a> => bool = "#is_nullable"`

2024-06-03 16:54 UTC, zth commented on src/components/SearchBox.res
> +    let isDiv = Nullable.toOption(el["type"])->Option.isSome
Ah, probably just a miss. Care to PR it?

2024-06-03 17:16 UTC, fhammerschmidt requested changes

2024-06-04 02:44 UTC, aspeddro commented on pages/docs/react/latest/forwarding-refs.mdx
> +    ->Nullable.toOption
Done https://github.com/rescript-association/rescript-lang.org/pull/876/commits/6d659e5007171c20dae3759fdcaf27b0b7004b67

2024-06-04 02:44 UTC, aspeddro commented on pages/docs/react/latest/hooks-ref.mdx
> +    ->Nullable.toOption
Done https://github.com/rescript-association/rescript-lang.org/pull/876/commits/6d659e5007171c20dae3759fdcaf27b0b7004b67

2024-06-04 02:44 UTC, aspeddro commented on pages/docs/react/latest/hooks-ref.mdx
> +    ->Nullable.toOption
Done https://github.com/rescript-association/rescript-lang.org/pull/876/commits/6d659e5007171c20dae3759fdcaf27b0b7004b67

2024-06-04 02:44 UTC, aspeddro commented on pages/docs/react/latest/refs-and-the-dom.mdx
> +    switch textInput.current->Nullable.toOption {
Done https://github.com/rescript-association/rescript-lang.org/pull/876/commits/6d659e5007171c20dae3759fdcaf27b0b7004b67

2024-06-04 02:44 UTC, aspeddro commented on pages/docs/react/latest/refs-and-the-dom.mdx
> +    ->Nullable.toOption
Done https://github.com/rescript-association/rescript-lang.org/pull/876/commits/6d659e5007171c20dae3759fdcaf27b0b7004b67

2024-06-04 02:44 UTC, aspeddro commented on src/ApiDocs.res
> +        ->Belt.SortArray.stableSortBy((v1, v2) => v1.name > v2.name ? 1 : -1)
Done https://github.com/rescript-association/rescript-lang.org/pull/876/commits/6d659e5007171c20dae3759fdcaf27b0b7004b67

2024-06-04 02:44 UTC, aspeddro commented on src/Packages.res
> +    ->Belt.SortArray.stableSortBy((a, b) => a["item"].searchScore > b["item"].searchScore ? -1 : 1)
Done https://github.com/rescript-association/rescript-lang.org/pull/876/commits/6d659e5007171c20dae3759fdcaf27b0b7004b67

2024-06-04 02:46 UTC, aspeddro commented on src/components/SearchBox.res
> +    let isDiv = Nullable.toOption(el["type"])->Option.isSome
Yes. I Opened a PR on Core. I'll leave `Js.Null Undefined.is Nullable` until a new version of Core is released

2024-06-04 02:49 UTC, aspeddro commented
More two commits here:
- https://github.com/rescript-association/rescript-lang.org/pull/876/commits/8bb5c90464fb2c6bf725169f15d05b7e68610c0a
- https://github.com/rescript-association/rescript-lang.org/pull/876/commits/901c244a8557f206e116f45e2244fd7fac9c4c0a

2024-06-04 05:24 UTC, fhammerschmidt approved these changes

2024-06-04 05:24 UTC, merged